services:
  web:
    build: .
    image: ${DOCKERHUB_USERNAME:-srgokuto}/ejercicio-docker-audit:latest
    container_name: tecnova-web
    restart: unless-stopped
    networks:
      - tecnova-net
    env_file:
      - .env
    environment:
      DB_HOST: db
      PORT: "5050"
    ports:
      - "5050:5050"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4
    container_name: tecnova-db
    restart: unless-stopped
    networks:
      - tecnova-net
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: tecnova-npm
    restart: unless-stopped
    networks:
      - tecnova-net
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: tecnova-uptime
    restart: unless-stopped
    networks:
      - tecnova-net
    ports:
      - "3001:3001"
    volumes:
      - uptime_kuma_data:/app/data

  dozzle:
    image: amir20/dozzle:latest
    container_name: tecnova-dozzle
    restart: unless-stopped
    networks:
      - tecnova-net
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dozzle_data:/data

volumes:
  db_data:
  npm_data:
  npm_letsencrypt:
  uptime_kuma_data:
  dozzle_data:

networks:
  tecnova-net:
    driver: bridge